################################################################################
# FUNDING.yml for Ultrahand-Overlay Repository
# Author: ppkantorski
# Description:
#   This FUNDING.yml file is used to configure the sponsor button for the Ultrahand Overlay
#   repository on GitHub. It specifies the supported funding model platforms and their
#   respective account information.
#
#   GitHub Repository: https://github.com/ppkantorski/Ultrahand-Overlay
#
################################################################################

github: ppkantorski
kofi: ppkantorski
